import {
  pgTable,
  serial,
  varchar,
  integer,
  boolean,
  numeric,
  timestamp,
  text,
} from 'drizzle-orm/pg-core';

export const warframes = pgTable('warframes', {
  id: serial('id').primaryKey(),
  uniqueName: varchar('unique_name', { length: 255 }),
  name: varchar('name', { length: 150 }).notNull(),
  type: varchar('type', { length: 100 }),
  isPrime: boolean('is_prime').default(false),
  aura: varchar('aura', { length: 100 }),
  releaseYear: integer('release_year'),
  releaseDate: varchar('release_date', { length: 20 }),
  description: text('description'),
  health: integer('health'),
  armor: integer('armor'),
  shield: integer('shield'),
  sprintSpeed: numeric('sprint_speed', { precision: 4, scale: 2 }),
  polarities: varchar('polarities', { length: 100 }).array(),
  sex: varchar('sex', { length: 10 }),
  imageName: varchar('image_name', { length: 500 }),
  wikiaThumbnail: varchar('wikia_thumbnail', { length: 500 }),
  wikiUrl: varchar('wiki_url', { length: 500 }),
  exalted: text('exalted').array(),
  createdAt: timestamp('created_at').defaultNow(),
});
